name: Test Only

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        type: choice
        options:
          - production
          - preview
      domain:
        description: 'Select domain'
        required: true
        type: choice
        options:
          - all
          - us
          - ca
          # - uk
          # - de
          # - fr
          # - es
          # - nl
          # - sw
          # - dk
      COHORT:
        description: 'Select cohort'
        required: true
        type: choice
        options:
          - All
          - Release Candidate
          - Customer Facing
          - Blue
          - Green
      unique:
        description: 'a unique id to allow remote tracking'
        required: false
        default: '(none)'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
